<?php
 // module/Game/view/game/game/add.phtml:

 $title = 'Add new game';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('game', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name_original'));
 echo $this->formRow($form->get('name_translated'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();