<?php
 // module/Game/view/game/game/delete.phtml:

 $title = 'Delete game';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($game->name_original); ?>' by
     '<?php echo $this->escapeHtml($game->name_translated); ?>'?
 </p>
 <?php
 $url = $this->url('game', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $game->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>